name: Update README
on: [push, workflow_dispatch]

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: 'Keyfactor/actions'
          path: './actions/'

      - uses: Keyfactor/jinja2-action@v1.2.0-multiple-data-files
        with:
          template: ./actions/readme-templates/readme.md.tpl
          output_file: README.md
          data_file: |
            integration-manifest.json
            ./actions/readme-templates/readme_shared_data.json
        env:
          GITHUB_TOKEN: ${{ secrets.SDK_SYNC_PAT }}
          
      - name: Show generated README.md
        run: echo $(cat README.md)
        
      - uses: ./actions/add-and-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: README.md --force
          message: Update generated README
          author_name: Keyfactor
          author_email: keyfactor@keyfactor.github.io
